#ifndef ALLCARDPCH_HPP
#define ALLCARDPCH_HPP
#include "Card/Altar.hpp"
#include "Card/AnimalPen.hpp"
#include "Card/BluePrint.hpp"
#include "Card/Brickyard.hpp"
#include "Card/Card.hpp"
#include "Card/CardPack.hpp"
#include "Card/Chest.hpp"
#include "Card/Combatable.hpp"
#include "Card/Corpse.hpp"
#include "Card/Equipable.hpp"
#include "Card/Food.hpp"
#include "Card/Garden.hpp"
#include "Card/Gold.hpp"
#include "Card/GreenHouse.hpp"
#include "Card/Harvestable.hpp"
#include "Card/House.hpp"
#include "Card/Kid.hpp"
#include "Card/Market.hpp"
#include "Card/Poop.hpp"
#include "Card/Resource.hpp"
#include "Card/Sawmill.hpp"
#include "Card/SlaughterHouse.hpp"
#include "Card/Smelter.hpp"
#include "Card/TravellingCart.hpp"
#include "Card/CardLeftNum.hpp"
#include "Card/CardRightNum.hpp"
#include "Card/CardTitle.hpp"
#include "Card/Milk.hpp"
#include "Card/Egg.hpp"
#include "Card/Bone.hpp"
#include "Card/BaseVillager.hpp"
#include "Card/Mob.hpp"
#include "Card/Animal.hpp"
#include "Card/Enemy.hpp"
#include "Card/Graveyard.hpp"
#include "Card/Portal.hpp"
#include "Card/Temple.hpp"
#include "Card/Building.hpp"
#include "Card/TreasureChest.hpp"
#include "Card/Shop.hpp"




#endif // !ALLCARDPCH_HPP
